###

POST http://localhost:3011/api/playlist HTTP/1.1
content-type: application/json

{
  "sort": "id",
  "order": "desc",
  "offset": 2,
  "limit": 1
}

###
GET http://localhost:3011/api/playlist/31 HTTP/1.1
content-type: application/json